// Generated by blinkc.js

package xmit;

public class Applied
{
  public long getFrom () { return m_From; }
  public void setFrom (long v) { m_From = v; }
  public int getCount () { return m_Count; }
  public void setCount (int v) { m_Count = v; }
  
  private long m_From;
  private int m_Count;
}

