// Generated by blinkc.js

package xmit;

public class Establish
{
  public long getTimestamp () { return m_Timestamp; }
  public void setTimestamp (long v) { m_Timestamp = v; }
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public int getKeepaliveInterval () { return m_KeepaliveInterval; }
  public void setKeepaliveInterval (int v) { m_KeepaliveInterval = v; }
  public java.lang.Object getCredentials () { return m_Credentials; }
  public boolean hasCredentials () { return m_Credentials != null; }
  public void clearCredentials () { m_Credentials = null; }
  public void setCredentials (java.lang.Object v) { m_Credentials = v; }
  
  private long m_Timestamp;
  private byte [] m_SessionId;
  private int m_KeepaliveInterval;
  private java.lang.Object m_Credentials;
}

