// Generated by blinkc.js

package xmit;

public class EstablishChallengeResponse
{
  public java.lang.String getSessionId () { return m_SessionId; }
  public void setSessionId (java.lang.String v) { m_SessionId = v; }
  public long getChallengeTimestamp () { return m_ChallengeTimestamp; }
  public void setChallengeTimestamp (long v) { m_ChallengeTimestamp = v; }
  public long getTimestamp () { return m_Timestamp; }
  public void setTimestamp (long v) { m_Timestamp = v; }
  public java.lang.Object getResponse () { return m_Response; }
  public void setResponse (java.lang.Object v) { m_Response = v; }
  
  private java.lang.String m_SessionId;
  private long m_ChallengeTimestamp;
  private long m_Timestamp;
  private java.lang.Object m_Response;
}

