// Generated by blinkc.js

package xmit;

public class Establish
{
  public long getTimestamp () { return m_Timestamp; }
  public void setTimestamp (long v) { m_Timestamp = v; }
  public java.lang.String getSessionId () { return m_SessionId; }
  public void setSessionId (java.lang.String v) { m_SessionId = v; }
  public long getKeepaliveInterval () { return m_KeepaliveInterval; }
  public void setKeepaliveInterval (long v) { m_KeepaliveInterval = v; }
  public java.lang.Object getCredentials () { return m_Credentials; }
  public boolean hasCredentials () { return m_Credentials != null; }
  public void clearCredentials () { m_Credentials = null; }
  public void setCredentials (java.lang.Object v) { m_Credentials = v; }
  
  private long m_Timestamp;
  private java.lang.String m_SessionId;
  private long m_KeepaliveInterval;
  private java.lang.Object m_Credentials;
}

