// Generated by blinkc.js

package xmit;

public class EstablishAck
{
  public java.lang.String getSessionId () { return m_SessionId; }
  public void setSessionId (java.lang.String v) { m_SessionId = v; }
  public long getRequestTimestamp () { return m_RequestTimestamp; }
  public void setRequestTimestamp (long v) { m_RequestTimestamp = v; }
  public long getTimestamp () { return m_Timestamp; }
  public void setTimestamp (long v) { m_Timestamp = v; }
  public long getKeepaliveInterval () { return m_KeepaliveInterval; }
  public void setKeepaliveInterval (long v) { m_KeepaliveInterval = v; }
  public long getNextSeqNo () { return m_NextSeqNo; }
  public boolean hasNextSeqNo () { return has_NextSeqNo; }
  public void clearNextSeqNo () { has_NextSeqNo = false; }
  public void setNextSeqNo (long v) { m_NextSeqNo = v; has_NextSeqNo = true; }
  
  private boolean has_NextSeqNo;
  
  private java.lang.String m_SessionId;
  private long m_RequestTimestamp;
  private long m_Timestamp;
  private long m_KeepaliveInterval;
  private long m_NextSeqNo;
}

