// Generated by blinkc.js

package xmit;

public class EstablishmentReject
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public long getRequestTimestamp () { return m_RequestTimestamp; }
  public void setRequestTimestamp (long v) { m_RequestTimestamp = v; }
  public EstablishmentRejectCode getCode () { return m_Code; }
  public void setCode (EstablishmentRejectCode v) { m_Code = v; }
  public java.lang.String getReason () { return m_Reason; }
  public boolean hasReason () { return m_Reason != null; }
  public void clearReason () { m_Reason = null; }
  public void setReason (java.lang.String v) { m_Reason = v; }
  
  private byte [] m_SessionId;
  private long m_RequestTimestamp;
  private EstablishmentRejectCode m_Code;
  private java.lang.String m_Reason;
}

