// Generated by blinkc.js

package xmit;

public enum EstablishmentRejectCode
{
  Unnegotiated (0),
  AlreadyEstablished (1),
  SessionBlocked (2),
  KeepaliveInterval (3),
  Credentials (4),
  Unspecified (5);
  
  private EstablishmentRejectCode (int val) { this.val = val; }
  public int getValue () { return val; }
  private final int val;
}

