// Generated by blinkc.js

package xmit;

public class FinishedReceiving
{
  public java.lang.String getSessionId () { return m_SessionId; }
  public void setSessionId (java.lang.String v) { m_SessionId = v; }
  
  private java.lang.String m_SessionId;
}

