// Generated by blinkc.js

package xmit;

public class FinishedReceiving
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  
  private byte [] m_SessionId;
}

