// Generated by blinkc.js

package xmit;

public class FinishedSending
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public long getLastSeqNo () { return m_LastSeqNo; }
  public void setLastSeqNo (long v) { m_LastSeqNo = v; }
  
  private byte [] m_SessionId;
  private long m_LastSeqNo;
}

