// Generated by blinkc.js

package xmit;

public class NegotiationResponse
{
  public long getRequestTimestamp () { return m_RequestTimestamp; }
  public void setRequestTimestamp (long v) { m_RequestTimestamp = v; }
  public java.lang.String getSessionId () { return m_SessionId; }
  public void setSessionId (java.lang.String v) { m_SessionId = v; }
  public FlowType getServerFlow () { return m_ServerFlow; }
  public void setServerFlow (FlowType v) { m_ServerFlow = v; }
  
  private long m_RequestTimestamp;
  private java.lang.String m_SessionId;
  private FlowType m_ServerFlow;
}

