// Generated by blinkc.js

package xmit;

public class NegotiationReject
{
  public long getRequestTimestamp () { return m_RequestTimestamp; }
  public void setRequestTimestamp (long v) { m_RequestTimestamp = v; }
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public java.lang.String getReason () { return m_Reason; }
  public void setReason (java.lang.String v) { m_Reason = v; }
  
  private long m_RequestTimestamp;
  private byte [] m_SessionId;
  private java.lang.String m_Reason;
}

