// Generated by blinkc.js

package xmit;

public class NotApplied
{
  public long getFromSeqNo () { return m_FromSeqNo; }
  public void setFromSeqNo (long v) { m_FromSeqNo = v; }
  public int getCount () { return m_Count; }
  public void setCount (int v) { m_Count = v; }
  
  private long m_FromSeqNo;
  private int m_Count;
}

