// Generated by blinkc.js

package xmit;

public class QueueProbe
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public long getKey () { return m_Key; }
  public void setKey (long v) { m_Key = v; }
  
  private byte [] m_SessionId;
  private long m_Key;
}

