// Generated by blinkc.js

package xmit;

public class Retransmission
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public long getNextSeqNo () { return m_NextSeqNo; }
  public void setNextSeqNo (long v) { m_NextSeqNo = v; }
  
  private byte [] m_SessionId;
  private long m_NextSeqNo;
}

