// Generated by blinkc.js

package xmit;

public class Retransmission
{
  public java.lang.String getSessionId () { return m_SessionId; }
  public void setSessionId (java.lang.String v) { m_SessionId = v; }
  public long getNextSeqNo () { return m_NextSeqNo; }
  public void setNextSeqNo (long v) { m_NextSeqNo = v; }
  
  private java.lang.String m_SessionId;
  private long m_NextSeqNo;
}

