// Generated by blinkc.js

package xmit;

public class RetransmitRequestResponse
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public long getRequestTimestamp () { return m_RequestTimestamp; }
  public void setRequestTimestamp (long v) { m_RequestTimestamp = v; }
  public long getFromSeqNo () { return m_FromSeqNo; }
  public void setFromSeqNo (long v) { m_FromSeqNo = v; }
  public int getCount () { return m_Count; }
  public void setCount (int v) { m_Count = v; }
  
  private byte [] m_SessionId;
  private long m_RequestTimestamp;
  private long m_FromSeqNo;
  private int m_Count;
}

