// Generated by blinkc.js

package xmit;

public class Sequence
{
  public long getNextSeqNo () { return m_NextSeqNo; }
  public void setNextSeqNo (long v) { m_NextSeqNo = v; }
  
  private long m_NextSeqNo;
}

