// Generated by blinkc.js

package xmit;

public class SnapshotRequest
{
  public java.lang.String getSessionId () { return m_SessionId; }
  public void setSessionId (java.lang.String v) { m_SessionId = v; }
  public long getTimestamp () { return m_Timestamp; }
  public void setTimestamp (long v) { m_Timestamp = v; }
  
  private java.lang.String m_SessionId;
  private long m_Timestamp;
}

