// Generated by blinkc.js

package xmit;

public class Snapshot
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public long getRequestTimestamp () { return m_RequestTimestamp; }
  public boolean hasRequestTimestamp () { return has_RequestTimestamp; }
  public void clearRequestTimestamp () { has_RequestTimestamp = false; }
  public void setRequestTimestamp (long v) { m_RequestTimestamp = v; has_RequestTimestamp = true; }
  public long getSeqNo () { return m_SeqNo; }
  public void setSeqNo (long v) { m_SeqNo = v; }
  public int getSegments () { return m_Segments; }
  public boolean hasSegments () { return has_Segments; }
  public void clearSegments () { has_Segments = false; }
  public void setSegments (int v) { m_Segments = v; has_Segments = true; }
  public int getSegment () { return m_Segment; }
  public boolean hasSegment () { return has_Segment; }
  public void clearSegment () { has_Segment = false; }
  public void setSegment (int v) { m_Segment = v; has_Segment = true; }
  public java.lang.Object [] getPayload () { return m_Payload; }
  public void setPayload (java.lang.Object [] v) { m_Payload = v; }
  
  private boolean has_RequestTimestamp;
  private boolean has_Segments;
  private boolean has_Segment;
  
  private byte [] m_SessionId;
  private long m_RequestTimestamp;
  private long m_SeqNo;
  private int m_Segments;
  private int m_Segment;
  private java.lang.Object [] m_Payload;
}

