// Generated by blinkc.js

package xmit;

public class StringIdentification
{
  public java.lang.String getIdentity () { return m_Identity; }
  public void setIdentity (java.lang.String v) { m_Identity = v; }
  
  private java.lang.String m_Identity;
}

