// Generated by blinkc.js

package xmit;

public class StringClassification
{
  public java.lang.String getDescription () { return m_Description; }
  public void setDescription (java.lang.String v) { m_Description = v; }
  
  private java.lang.String m_Description;
}

