// Generated by blinkc.js

package xmit;

public enum TerminationCode
{
  Finished (0),
  UnspecifiedError (1),
  ReRequestOutOfBounds (2),
  ReRequestInProgress (3),
  Timeout (4);
  
  private TerminationCode (int val) { this.val = val; }
  public int getValue () { return val; }
  private final int val;
}

