// Generated by blinkc.js

package xmit_once;

public class Applied
{
  public int getFrom () { return m_From; }
  public void setFrom (int v) { m_From = v; }
  public int getTo () { return m_To; }
  public void setTo (int v) { m_To = v; }
  
  private int m_From;
  private int m_To;
}

