// Generated by blinkc.js

package xmit_once;

public class NotApplied
{
  public long getToken () { return m_Token; }
  public void setToken (long v) { m_Token = v; }
  public NotAppliedReason getReason () { return m_Reason; }
  public void setReason (NotAppliedReason v) { m_Reason = v; }
  
  private long m_Token;
  private NotAppliedReason m_Reason;
}

