// Generated by blinkc.js

package xmit_once;

public class QueryLatest
{
  public byte [] getSessionId () { return m_SessionId; }
  public boolean hasSessionId () { return m_SessionId != null; }
  public void clearSessionId () { m_SessionId = null; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  
  private byte [] m_SessionId;
}

