// Generated by blinkc.js

package xmit_once;

public class Status
{
  public byte [] getSessionId () { return m_SessionId; }
  public void setSessionId (byte [] v) { m_SessionId = v; }
  public long getLastAppliedToken () { return m_LastAppliedToken; }
  public boolean hasLastAppliedToken () { return has_LastAppliedToken; }
  public void clearLastAppliedToken () { has_LastAppliedToken = false; }
  public void setLastAppliedToken (long v) { m_LastAppliedToken = v; has_LastAppliedToken = true; }
  
  private boolean has_LastAppliedToken;
  
  private byte [] m_SessionId;
  private long m_LastAppliedToken;
}

