// Generated by blinkc.js

package test;

public class Ping
{
  public int getValue () { return m_Value; }
  public void setValue (int v) { m_Value = v; }
  public int getPongCount () { return m_PongCount; }
  public void setPongCount (int v) { m_PongCount = v; }
  
  private int m_Value;
  private int m_PongCount;
}

